#!/bin/sh

#
# jupyter tool
#
/usr/bin/invoke_app "$@" -t alpsinteract \
                         -C "start_jupyter -A -T @tool -t alpsinteract.ipynb" \
                         -u anaconda-7 \
                         -r none \
                         -w headless

